batch_size: 8
conv_ch: 192
dropout: 0.5
epochs: 2400
loss: mse_cosine_loss
loss_weighting: 'mse:  1, cos_prox: 0.1'
lr_schedule:
  gamma: 0.1
  milestones:
  - 200
max_shift: 5
optimizer:
  amsgrad: false
  beta_1: 0.8999999761581421
  beta_2: 0.9990000128746033
  decay: 0.0
  epsilon: 1.0e-07
  lr: 0.0010000000474974513
roi: ROI_VC
scale_type: standard
val_batch_size: 20
