batch_size: 8
dropout: 0.5
epochs: 600
loss: combined_loss
lr_schedule: 'e<25: 0.001, e>24: 0.0001'
max_shift: 5
optimizer:
  decay: 0.0
  lr: 0.0010000000474974513
  momentum: 0.8999999761581421
  nesterov: true
roi: ROI_VC
scale_type: standard
val_batch_size: 20
