batch_size: 8
dropout: 0.5
epochs: 100
loss: combined_loss
lr_schedule: 'e<5: 0.1, e>5: 0.01, e>35 : 0.001'
max_shift: 5
optimizer:
  decay: 0.0
  lr: 0.10000000149011612
  momentum: 0.8999999761581421
  nesterov: true
roi: ROI_VC
scale_type: standard
val_batch_size: 20
